### ISSUE TITLE
[轻小说机翻机器人]在算力不足时的算力浪费隐患

### ISSUE THREAD

**Issue by pingplug** [1PercentSync/sakura-share#2]
章节分段翻译失败→重新开始翻译→分配新节点→缓存失效，重新翻译已翻译分段
没想到在算力不足的情况下有成倍的算力浪费效果，加剧算力不足的压力。。。

**Comment by 1PercentSync** [comment]
确实有这样的问题，sakura即将基于qwen2.5训练新版本，到那时由于gqa的存在会大幅提高可用槽位的数量。
也有不直接暴露翻译端点的是由一个中心的翻译器排队翻译后上传的解决方案。

**Comment by pingplug** [comment]
感觉像是进入了地狱，现存4个节点，某个章节分了8段，第四段行数不匹配，需要逐行翻译。
经常在第四段逐行的时候失败，然后重翻。。。
网站会检查模型指纹，而指纹与模型和硬件都有关系，节点一换就GG。。。
缓存全清，重头开始。。。
重试了几十遍未能翻译，放弃。。。

建议：
1. 如果知道请求来源的IP，做有亲和性的分配，比如一小时内只分配给同一个节点
2. 增加排队机制，没有节点不要先返回失败
3. 如果能知道翻译的是第几段，也许可增加排序的优先级权重，例如权重是段数的平方根？

**Comment by PiDanShouRouZhouXD** [comment]
> 感觉像是进入了地狱，现存4个节点，某个章节分了8段，第四段行数不匹配，需要逐行翻译。 经常在第四段逐行的时候失败，然后重翻。。。 网站会检查模型指纹，而指纹与模型和硬件都有关系，节点一换就GG。。。 缓存全清，重头开始。。。 重试了几十遍未能翻译，放弃。。。
> 
> 建议：
> 
> 1. 如果知道请求来源的IP，做有亲和性的分配，比如一小时内只分配给同一个节点
> 2. 增加排队机制，没有节点不要先返回失败
> 3. 如果能知道翻译的是第几段，也许可增加排序的优先级权重，例如权重是段数的平方根？

第三点由于绿站限制做不了，其他的已经修改了。目前的逻辑是优先分配同一个节点，不够了再分配其他节点，并增加了排队机制。
